spring:
  application:
    name: report-ms
  profiles:
    default: prod
  config:
    import: 'optional:configserver:${CONFIG_SERVER_HOST}'
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${BROKER_URL}
      function:
        bindings:
          consumerReport-out-0:
            destination: consumerReport
server:
  servlet:
    context-path: /report-ms
  port: 7070
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
